# Generated by Django 3.2.7 on 2021-09-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
