# Generated by Django 3.2.7 on 2021-09-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_favorite_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='favorite_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
