# Generated by Django 3.2.7 on 2021-09-25 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('service_type', models.CharField(choices=[('Places', 'Places'), ('Planers', 'Planers'), ('MusicBands', 'MusicBands'), ('PhotoSession', 'PhotoSession'), ('Fashion', 'Fashion'), ('Cars', 'Cars'), ('Trip', 'Trip')], default='Places', max_length=64)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('location_link', models.CharField(max_length=256)),
                ('city', models.CharField(choices=[('Amman', 'Amman'), ('Irbid', 'Irbid'), ('Zarqa', 'Zarqa'), ('Al-Mafraq', 'Al-Mafraq'), ('Jarash', 'Jarash'), ('Ajloun', 'Ajloun'), ('As-Salt', 'As-Salt'), ('Madaba', 'Madaba'), ('karak', 'karak'), ('Tafilah', 'Tafilah'), ('Maan', 'Maan'), ('Aqaba', 'Aqaba')], default='Amman', max_length=64)),
                ('place_type', models.CharField(choices=[('Hall', 'Hall'), ('Restaurant', 'Restaurant'), ('Farm', 'Farm')], default='Hall', max_length=64)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
