# Generated by Django 3.2.7 on 2021-09-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyistic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='emailname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='fashion',
            name='emailname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='musicbands',
            name='emailname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='parties',
            name='emailname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='photosession',
            name='emailname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='places',
            name='emailname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='planners',
            name='emailname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='trip',
            name='emailname',
            field=models.CharField(default='', max_length=256),
        ),
    ]
